-- supabase/seed.sql
-- GENERATED by scripts/crawl-catalog.ts — DO NOT EDIT BY HAND.
-- Regenerate with: bun run crawl:catalog
--
-- Point-in-time snapshot (2026-07-07T08:41:12.496Z) of the currently popular,
-- REAL provider / skill / mcp entries crawled from public sources:
--   provider → OpenRouter, skill → GitHub, mcp → PulseMCP.
-- Plus the 3 fixed TEST providers (local / yls / skyapi, tagged 'test').
-- Counts: mcp=10, provider=10, skill=10 (+3 test providers).

-- ── Publishers (test publishers + crawled) ──────────────────────────────────
INSERT INTO publishers (slug, name, avatar_url, tier, bio) VALUES
  ('agent-store', 'Agent Store', 'https://api.dicebear.com/9.x/shapes/svg?seed=agent-store', 'official', 'Agent Store 官方内置组件。'),
  ('yls-me', 'YLS.me', 'https://api.dicebear.com/9.x/shapes/svg?seed=yls', 'verified', '已验证的第三方模型中转服务。'),
  ('skyapi', 'SkyAPI', 'https://api.dicebear.com/9.x/shapes/svg?seed=skyapi', 'community', '稳定线路、免翻墙接入 Claude Code 的第三方中转服务。'),
  ('affaan-m', 'affaan-m', 'https://avatars.githubusercontent.com/u/124439313?v=4', 'community', NULL),
  ('akashml', 'AkashML', 'https://api.dicebear.com/9.x/shapes/svg?seed=akashml', 'community', NULL),
  ('arcee-ai', 'Arcee AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=arcee-ai', 'community', NULL),
  ('assistant-ui', 'assistant-ui', 'https://github.com/assistant-ui.png', 'community', NULL),
  ('cerebras', 'Cerebras', 'https://api.dicebear.com/9.x/shapes/svg?seed=cerebras', 'community', NULL),
  ('chromedevtools', 'chromedevtools', 'https://github.com/chromedevtools.png', 'community', NULL),
  ('czlonkowski', 'czlonkowski', 'https://github.com/czlonkowski.png', 'community', NULL),
  ('deusdata', 'deusdata', 'https://github.com/deusdata.png', 'community', NULL),
  ('glips', 'glips', 'https://github.com/glips.png', 'community', NULL),
  ('microsoft', 'microsoft', 'https://github.com/microsoft.png', 'community', NULL),
  ('morph', 'Morph', 'https://api.dicebear.com/9.x/shapes/svg?seed=morph', 'community', NULL),
  ('openai', 'OpenAI', 'https://api.dicebear.com/9.x/shapes/svg?seed=openai', 'official', NULL),
  ('pydantic', 'pydantic', 'https://github.com/pydantic.png', 'community', NULL),
  ('reka', 'Reka', 'https://api.dicebear.com/9.x/shapes/svg?seed=reka', 'community', NULL),
  ('sambanova', 'SambaNova', 'https://api.dicebear.com/9.x/shapes/svg?seed=sambanova', 'community', NULL),
  ('stealth', 'Stealth', 'https://api.dicebear.com/9.x/shapes/svg?seed=stealth', 'community', NULL),
  ('stepfun', 'StepFun', 'https://api.dicebear.com/9.x/shapes/svg?seed=stepfun', 'community', NULL),
  ('upstash', 'upstash', 'https://github.com/upstash.png', 'community', NULL),
  ('yamadashy', 'yamadashy', 'https://github.com/yamadashy.png', 'community', NULL),
  ('z-ai', 'Z.AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=z-ai', 'community', NULL),
  ('zilliztech', 'zilliztech', 'https://github.com/zilliztech.png', 'community', NULL);

-- ── TEST providers (always present, real configs) ───────────────────────────
-- Provider: local (built-in relay) — the endpoint Claude/Codex point at; forwards
-- to upstream providers by level. No upstream API key. Rendered specially in the
-- CLI client (LOCAL_PROVIDER_SENTINEL __local__); this catalog row is its store listing.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'local',
  '本地中转',
  '内置本地中转：将 Claude Code / Codex 的 baseURL 指向本机监听端口，请求按 Level 优先级转发到已配置的上游供应商，失败自动降级。无需 API 密钥。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'agent-store'),
  ARRAY['claude','codex'], ARRAY['relay','local','内置','test'], 0, 5.0, 'published',
  $${"steps":[]}$$,
  $${"configSchema":{},"supportedModels":[]}$$
);

-- Provider: yls (伊莉思 Code) — real China relay for Codex CLI. Pre-fills the codex
-- endpoint connection on install; user supplies the Bearer API key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'yls',
  'YLS Code 中转',
  '伊莉思 Code 中转服务，国内直连免翻墙接入 Codex CLI（GPT-5 Code）与 Claude Code；此预设接入其 Codex 端点，按订阅计费。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'yls-me'),
  ARRAY['codex'], ARRAY['relay','codex','国产中转','test'], 32000, 4.7, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"https://code.ylsagi.com/codex","authType":"bearer","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (Bearer)"},"baseUrl":{"type":"string","description":"API 地址","default":"https://code.ylsagi.com/codex"},"authType":{"type":"string","default":"bearer"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["gpt-5-codex","gpt-5"]}$$
);

-- Provider: skyapi — real China relay for Claude Code (Anthropic protocol). Pre-fills
-- the claude endpoint connection on install; user supplies the x-api-key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skyapi',
  'SkyAPI 中转',
  'SkyAPI 中转服务，稳定线路免翻墙接入 Claude Code，兼容 Cursor / Cline / Windsurf 等客户端。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'skyapi'),
  ARRAY['claude'], ARRAY['relay','claude','国产中转','test'], 21000, 4.5, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"http://150.158.2.79:8888","authType":"anthropic","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (x-api-key)"},"baseUrl":{"type":"string","description":"API 地址","default":"http://150.158.2.79:8888"},"authType":{"type":"string","default":"anthropic"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["claude-opus-4-8","claude-sonnet-5","claude-haiku-4-5-20251001","claude-opus-4-5"]}$$
);

-- ── Crawled items (real, popularity-ranked) ─────────────────────────────────
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'playwright-mcp', 'Playwright Browser Automation', 'Enables web browser control for navigating websites, capturing page snapshots, interacting with elements, and taking screenshots through Playwright''s automation capabilities.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'microsoft'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 83762772, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @playwright/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'chrome-devtools-mcp', 'Chrome DevTools', 'Provides direct Chrome browser control through DevTools for web automation, debugging, and performance analysis using accessibility tree snapshots for reliable element targeting, automatic page event handling, and integrated performance tracing with actionable insights.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'chromedevtools'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 32499266, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y chrome-devtools-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'upstash-context7-mcp', 'Context7 (Documentation Database)', 'Connects to Context7.com''s documentation database to provide up-to-date library and framework documentation with intelligent project ranking and customizable token limits.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'upstash'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 25020069, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @upstash/context7-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'assistant-ui-react', 'Assistant UI', 'The MCP server tools have been designed to allow an agent to query the specific information it needs to complete an assistant-ui related task - for example: implementing chat components, integrating with different runtimes, understanding component architecture, and troubleshooting issues.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'assistant-ui'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 16651443, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @assistant-ui/react","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'n8n-mcp', 'n8n', 'Integrates with n8n workflow automation platform to provide conversational access to 525+ nodes including AI-capable nodes and triggers, enabling natural language workflow creation, validation, and management without requiring direct platform knowledge.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'czlonkowski'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 3192432, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y n8n-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'figma-developer-mcp', 'Figma Context', 'Integrates with Figma''s design platform API to enable AI-driven design operations, asset management, and team collaboration within Figma workflows.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'glips'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 2860415, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y figma-developer-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'repomix', 'RepoMix', 'Package codebases into AI-friendly single files with intelligent code structure preservation and token optimization.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'yamadashy'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 2411926, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y repomix","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'zilliz-claude-context-mcp', 'Claude Context', 'Provides semantic code search and indexing using vector embeddings and AST-based code splitting, enabling natural language queries across codebases with automatic file filtering and support for multiple embedding providers and vector databases.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'zilliztech'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 58629, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @zilliz/claude-context-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'codebase-memory-mcp', 'Codebase Memory', 'Codebase knowledge graph for AI agents — 159 languages, sub-ms queries, 99% fewer tokens.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'deusdata'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 11132, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y codebase-memory-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'pydantic-mcp-run-python', 'Python Sandbox', 'Provides a browser-compatible Python execution environment with package management capabilities for running code snippets safely without requiring a backend Python installation.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'pydantic'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 5641, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @pydantic/mcp-run-python","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'arcee-ai-provider', 'Arcee AI', 'Arcee AI：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'arcee-ai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'sambanova-provider', 'SambaNova', 'SambaNova：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'sambanova'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'reka-provider', 'Reka', 'Reka：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'reka'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'cerebras-provider', 'Cerebras', 'Cerebras：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'cerebras'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'morph-provider', 'Morph', 'Morph：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'morph'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'stealth-provider', 'Stealth', 'Stealth：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'stealth'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'akashml-provider', 'AkashML', 'AkashML：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'akashml'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'openai-provider', 'OpenAI', 'OpenAI：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'openai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'z-ai-provider', 'Z.AI', 'Z.AI：OpenRouter 上的真实推理服务供应商（总部 SG）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'z-ai'),
  ARRAY['claude','codex'], ARRAY['provider','sg'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'stepfun-provider', 'StepFun', 'StepFun：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'stepfun'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-introspection-debugging', 'agent-introspection-debugging', 'Structured self-debugging workflow for AI agent failures using capture, diagnosis, contained recovery, and introspection reports.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-introspection-debugging/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-sort', 'agent-sort', 'Build an evidence-backed ECC install plan for a specific repo by sorting skills, commands, rules, hooks, and extras into DAILY vs LIBRARY buckets using parallel repo-aware review passes. Use when ECC should be trimmed to what a project actually needs instead of loading the full bundle.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-sort/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-api-design', 'api-design', 'REST API design patterns including resource naming, status codes, pagination, filtering, error responses, versioning, and rate limiting for production APIs.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/api-design/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-article-writing', 'article-writing', 'Write articles, guides, blog posts, tutorials, newsletter issues, and other long-form content in a distinctive voice derived from supplied examples or brand guidance. Use when the user wants polished written content longer than a paragraph, especially when voice consistency, structure, and credibili',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/article-writing/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/article-writing/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/article-writing/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-backend-patterns', 'backend-patterns', 'Backend architecture patterns, API design, database optimization, and server-side best practices for Node.js, Express, and Next.js API routes.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/backend-patterns/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/backend-patterns/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/backend-patterns/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-benchmark-methodology', 'benchmark-methodology', '>-',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/benchmark-methodology/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/benchmark-methodology/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/benchmark-methodology/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-brand-discovery', 'brand-discovery', '>-',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-discovery/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-discovery/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/brand-discovery/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-brand-voice', 'brand-voice', 'Build a source-derived writing style profile from real posts, essays, launch notes, docs, or site copy, then reuse that profile across content, outreach, and social workflows. Use when the user wants voice consistency without generic AI writing tropes.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-voice/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-voice/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/brand-voice/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-bun-runtime', 'bun-runtime', 'Bun as runtime, package manager, bundler, and test runner. When to choose Bun vs Node, migration notes, and Vercel support.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/bun-runtime/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/bun-runtime/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/bun-runtime/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-coding-standards', 'coding-standards', 'Baseline cross-project coding conventions for naming, readability, immutability, and code-quality review. Use detailed frontend or backend skills for framework-specific patterns.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226797, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/coding-standards/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/coding-standards/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/coding-standards/SKILL.md"}}'::jsonb
);

